server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath= /(?<segment>.*), /api/v1/dev/$\{segment}
      routes:
        #
        # http:/localhost/auth/***** will be catched and redirected to http:/localhost:9090/auth/*****
        - id: auth-micro-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9090
        # redirect when service is down
          filters:
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallbackauth


        - id: user-micro-service
          predicates:
            - Path=/user/**
          uri: http://localhost:9093
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallbackuser

