server:
  port: 9999
spring:
  elasticsearch:
    uris: http://localhost:9200
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-micro-service

myUrls:
  userServiceUrl: ${ETRADE_URLS_USER}
myJwt:
  passwordKey: ${ETRADE_JWT_PASSWORD_KEY}