server:
  port: 9093
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-micro-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserDB
#    url: jdbc:postgresql://${ETRADE_PG_GCLOUD_URL}/UserDB
    username: ${ETRADE_PG_USERNAME}
    password: ${ETRADE_PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
myUrls:
  userServiceUrl: ${ETRADE_URLS_USER}
myJwt:
  passwordKey: ${ETRADE_JWT_PASSWORD_KEY}